media:
  input: images
  output: /images

content:
  - name: products
    label: Products
    label_singular: Product
    type: collection
    path: data/products
    create: true
    format: yaml-frontmatter
    filename: "{{slug}}.md"
    fields:
      - name: title
        label: Product Title
        type: string
        required: true
      - name: description
        label: Description
        type: markdown
        required: true
      - name: image
        label: Product Image
        type: image
        required: true
      - name: price
        label: Price (BDT)
        type: number
      - name: specs
        label: Specifications
        type: list
        fields:
          - name: key
            label: Spec Name (e.g. Battery, Display)
            type: string
          - name: value
            label: Value
            type: string