content:
  - name: products
    label: Products
    path: data/products.json
    type: file   # single file
    format: json
    fields:
      # fields array of objects
      - name: title
        label: Title
        type: string
      # etc, but for array, it's a bit different – Pages CMS list support করে